services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODE=${MODE:-dev}
    volumes:
      - ./:/app
# to test output copying, uncomment the following line:
#      - /tmp/output:/output
